Image,Name,Short Bio,Subject Tags,Long Bio,Location,Rate,Online Teaching,Total Teaching,Location
,Varun Valsan,"Unity3d, unreal engine, AR, VR., Game dev",AR JAVA Unity3d gaming Virtual Reality Development,"Hi There I am your friendly neighbourhood tutor, I have more than 5 years of experience in XR technology which includes AR, VR and game development. As a teacher my moto is simple which is ""Your pain is my pain and your gain is my gain"", I would be involved in the usecases with you to an extend that by the end of the project you would feel like...",Kerala,"₹4,000–10,000/hour",4.0 yr.,4.0 yr.,Not present
,Shubham Tomar,Sr. iOS Engineer,AR Swift Firebase Realtime Database Data Structure and Algorithms iOS Application Development,"Post graduated in 2017, working as a Sr. iOS developer made many apps live on appstore.expertise in Xcode, swift, data structure, architecture, design patterns, database, automation, firebase, notifications, Xcode instruments, optimisation, memory leaks, memory graph, build speed, multimode, Apple design principals, Google map, Google services,...",Haryana,"₹1,000–3,000/hour",0.0 yr.,3.0 yr.,Not present
https://userphotos2.teacheron.com/1393642-78025.jpg,Sahil Mune,Lead Application Developer (XR technology),AR Augmented Reality AWS Virtual Reality Game Design and Development,"From game dev to AR/VR/XR to Amazon Web Services, I've dabbled with a wide variety of today's cutting-edge tech stacks. I've designed and built cutting-edge apps for multinational corporations in the United States and the United Kingdom. Among my most recent projects are a location-based AR app powered by serverless architecture on AWS and a...",Maharashtra,"₹900–2,000/hour",1.0 yr.,4.0 yr.,100 km
https://userphotos2.teacheron.com/931248-25196.jpg,Sanchit Sharma,I am a passionate Game developer & AR/VR developer,5.0,4,AR Unity 3d Virtual Reality C# Unity,2 More,Toggle Dropdown,Game Development Game Design and Development,"Hello,I am the Lead Developer of Bladers Multiplayer, a game that has more than 500K+ happy players (& counting) around the world.I am passionate about games, Game development & AR/VR development, not just on paper but I have won numerous hackathons, the Winner of the NASA Space Apps Hackathon, Winner of the Varcoe IIT Bbsr Hackathon, Winner...",Madhya Pradesh,"₹2,000–3,000/hour",3.0 yr.,4.0 yr.,Not present
,Ashok Kumar,"Unity3D Trainer, Augmented Reality Trainer, Python",AR Python Unity 3d Game Development,"Students are struggling in the way of how to apply the concepts that they have learned if they get start Development Getting know about the concepts are easy, but the lack of logical and analytical skills, make students feel like they are unfit. I strongly focus on make them to think logically and help them to identify where to apply which...",Tamil Nadu,"₹400–1,000/hour",5.0 yr.,10.0 yr.,Not present
https://userphotos2.teacheron.com/1419645-08636.jpg,Gurudath Tulupule,"App developer, Coding,Teaching, Student",Augmented Reality Maths Hindi Science,2 More,Toggle Dropdown,Kannada Android App Development,"Im Gurudath Tulupule and im from a rural village called Aladka near dharmastala. Im really good at teaching maths,kannada,English,hindi as I have 2 sister whom I teach a lot. Im also an android and Augmented reality app developer. I have conducted many seminars on app development and I have trained 10-15 students to develop apps and publish it on...",Karnataka,"₹250–1,000/hour",2.0 yr.,2.0 yr.,Not present
https://userphotos2.teacheron.com/1240758-55692.jpg,Amandeep Singh,Augmented Reality & Virtual Reality Expert,5.0,3,Augmented Reality Virtual Reality C# Unity Mixed Reality Game Design and Development,"Teaching about Metaverse is my passion. I love to share my knowledge, mistakes, failures & experiences with my students so that they can learn and achieve great success in their careers and goals.My teaching methodology is simple. Teach them using practical, fun exercised, plus in their language which they can relate to and in most friendly...",Uttarakhand,"₹1,500–10,000/hour",5.0 yr.,5.0 yr.,Not present
https://userphotos2.teacheron.com/50198-39311h.jpg,Prabhat Shukla,Software specilist,Augmented Reality C/C++ C# JAVA,16 More,Toggle Dropdown,Science Python Zoology ASP.NET MVC ADO.NET Oracle JIRA Design patterns Agile AWS MS SQL Web Services (SOAP/REST) PySpark .NET Core GIT Angular,"As I have given enough time to corporate I know what students want, and how to make them happy using skil enhancement and knowledge sharing.Students can approach me for the followings ASP.Net, C#,WCF,WebApi,COM,MVC.NetC/C++,Phyton,OOPS, SQL,Oracle,HTML,javascript,AngularJs,Reactjs,knockOut, jquery,agile,Mathematics, Physics,...",Maharashtra,"₹500–2,500/hour",6.0 yr.,9.0 yr.,Not present
https://userphotos2.teacheron.com/1558154-97784.jpg,Nagarjuna Vatti,"Unity 3D, AR and VR",AR and VR Unity 3d,"Passionate about the fields of AR/VR/MR. I have some good experience in developing AR projects with Unity 3D, Unreal and Vuforia. I am a certified Unity3D (AR/VR) developer from TechXR in collaboration with one of the reputed universities in India IIT Roorkee. Learning should always be fun so my teaching primarily includes interesting ppts and...",Maharashtra,"₹1,000–5,000/hour",1.0 yr.,1.0 yr.,Not present
,Kaarthik Ananth B,AR/VR/MR,AR/VR/MR,"I am a Prolific AR/VR/MR tutor in Unity.The Organizations which I had worked previously employed for teaching as well as ongoing projects.That makes me a great tutor in AR/VR/MR.I wil teaching through Google Meet,Zoom with a good interaction and demonstration from examples.My teaching method is online.My teaching style would be more practical so...",Puducherry,"₹500–1,000/hour",1.7 yr.,1.7 yr.,Not present
https://userphotos2.teacheron.com/1097284-57487.jpeg,Ankit Arora,Game Developer,AR/VR/MR Unity 3d Unreal Engine Maths (CBSE) Game Design and Development,"Hi guys, As you can see from my profile I have a degree in Game Design and Development and why I think I am better than others is because the way I have been taught, I believe was the right way, where more focus was on learning by doing more and more. We made so many projects and that really helped me in securing a nice job right after college....",Chandigarh,"₹500–2,000/hour",0.5 yr.,1.5 yr.,10 km
,Bharath,PTC Creo all versions all modules,"ARCore, Vuforia Casting Windchill SolidWorks 3D Software PTC Creo",Teaching style:i am a good communicator and professional trainer of PTC and i am only interested in online trainings and hands on support will be provided from my side and the charges included with hands on time and will be providing all the training content and materials.and i want to make my student strong professionally and i have trained...,Karnataka,"₹1,000–1,500/hour",3.0 yr.,5.0 yr.,Not present
